### lint

[tool.poe.tasks.lint]
help = "Run Ruff linter."
deps = ["_clone:ensure-repos:qpy"]
shell = """
  for repo in $_repos; do
    echo -e "${COLOR_TASK}[lint] ${COLOR_REPO}(${repo})${COLOR_OFF}"
    ruff check --config ./questionpy/$repo/pyproject.toml ./questionpy/$repo
    if [ "$repo" = "sdk" ]; then
      npm --prefix "${POE_ROOT}/questionpy/sdk/frontend" run lint
    fi
  done
"""
uses = { _repos = "_utils:parse-repos $repos" }

  [[tool.poe.tasks.lint.args]]
  name = "repos"
  positional = true
  multiple = true
  help = "List of repositories to lint (sdk, server or all)."
  default = "all"
