### qpy:serve

[tool.poe.tasks."qpy:serve"]
help = "Run QPy dev server."
sequence = [
  { cmd = 'echo -e "${COLOR_TASK}[qpy:serve]${COLOR_OFF}"' },
  "_qpy:serve",
]

### qpy:watch

[tool.poe.tasks."qpy:watch"]
help = "Run QPy dev server (watch mode)."
sequence = [
  { cmd = 'echo -e "${COLOR_TASK}[qpy:watch]${COLOR_OFF}"' },
  "_qpy:watch",
]

### private tasks

[tool.poe.tasks."_qpy:ensure-config"]
cwd = "./questionpy/server"
shell = """
  if [[ ! -f config.ini ]]; then
    cp config.example.ini config.ini
  fi
"""

[tool.poe.tasks."_qpy:ensure-cache-dir"]
cwd = "./questionpy/server"
cmd = "mkdir -p cache/packages cache/repo_index"

[tool.poe.tasks."_qpy:serve"]
cwd = "./questionpy/server"
cmd = "python -m questionpy_server"
deps = [
  "_repos:clone:ensure-repos-qpy",
  "_qpy:ensure-config",
  "_qpy:ensure-cache-dir",
]

[tool.poe.tasks."_qpy:watch"]
cwd = "./questionpy/server"
cmd = "watchmedo auto-restart --pattern '*.py' --directory \"${POE_ROOT}/questionpy/common/questionpy_common\" --directory \"${POE_ROOT}/questionpy/server/questionpy_server\" --recursive --debounce-interval 1 python -- -m questionpy_server"
deps = [
  "_repos:clone:ensure-repos-qpy",
  "_qpy:ensure-config",
  "_qpy:ensure-cache-dir",
]
