### qpy:serve

[tool.poe.tasks."qpy:serve"]
help = "Run QPy dev server."
cwd = "./questionpy/server"
cmd = "python -m questionpy_server"
use_exec = true
deps = [
  "_repos:clone:ensure-repos-qpy",
  "_qpy:ensure-config",
  "_qpy:ensure-cache-dir",
]

### qpy:watch

[tool.poe.tasks."qpy:watch"]
help = "Run QPy dev server (watch mode)."
cwd = "./questionpy/server"
# TODO
cmd = "echo watchmedo auto-restart --pattern *.py --recursive --signal SIGTERM  python app.py"
use_exec = true
deps = [
  "_repos:clone:ensure-repos-qpy",
  "_qpy:ensure-config",
  "_qpy:ensure-cache-dir",
]

### private tasks

[tool.poe.tasks."_qpy:ensure-config"]
cwd = "./questionpy/server"
shell = """
  if [[ ! -f config.ini ]]; then
    cp config.example.ini config.ini
  fi
"""

[tool.poe.tasks."_qpy:ensure-cache-dir"]
cwd = "./questionpy/server"
cmd = "mkdir -p cache/packages cache/repo_index"
