### repos:clone

[tool.poe.tasks."repos:clone"]
help = "Clone all repositories."
sequence = [
  { cmd = 'echo -e "${COLOR_TASK}[repos:clone]${COLOR_OFF}"' },
  "_repos:clone:ensure-repos-qpy",
  "_repos:clone:ensure-repos-qpy-qtype",
  "_repos:clone:ensure-repos-moodle",
]

[tool.poe.tasks."repos:sync-tooling"]
help = "Ensure repos tooling config is in sync."
deps = ["_repos:clone:ensure-repos-qpy"]
sequence = [
  "_repos:sync-tooling:sync-ruff-defaults",
]

### private tasks

[tool.poe.tasks."_repos:clone:ensure-repos-qpy"]
sequence = [
  "_utils:git-clone $REPO_QUESTIONPY_COMMON       ./questionpy/common",
  "_utils:git-clone $REPO_QUESTIONPY_DOCS         ./questionpy/docs",
  "_utils:git-clone $REPO_QUESTIONPY_SDK          ./questionpy/sdk",
  "_utils:git-clone $REPO_QUESTIONPY_SERVER       ./questionpy/server",
]

[tool.poe.tasks."_repos:clone:ensure-repos-qpy-qtype"]
ref = "_utils:git-clone $REPO_MOODLE_QTYPE_QUESTIONPY ./questionpy/moodle-qtype"

[tool.poe.tasks."_repos:clone:ensure-repos-moodle"]
sequence = [
  "_utils:git-clone $REPO_MOODLE                  ./vendor/moodle             --branch $REPO_MOODLE_TAG",
  "_utils:git-clone $REPO_MOODLE_DOCKER           ./vendor/moodle-docker      --branch main",
]

[tool.poe.tasks."_repos:sync-tooling:sync-ruff-defaults"]
shell = '''
  for repo in common sdk server; do
    if cmp -s ./ruff_defaults.toml questionpy/$repo/ruff_defaults.toml; then
      echo -ne "${COLOR_TASK}[repos:sync-tooling:ruff-default] ${COLOR_REPO}"
      printf '%-8s' "(${repo})"
      echo -e " ${COLOR_MSG}ruff_defaults.toml up-to-date${COLOR_OFF}"
    else
      cp ruff_defaults.toml questionpy/$repo/ruff_defaults.toml
      echo -ne "${COLOR_TASK}[repos:sync-tooling:ruff-default] ${COLOR_REPO}"
      printf '%-8s' "(${repo})"
      echo -e " ${COLOR_WARN}Sync'd ruff_defaults.toml${COLOR_OFF}"
    fi
  done
'''
