### tox

[tool.poe.tasks.tox]
help = "Run tox."
deps = ["_git:clone:ensure-repos-qpy"]
cmd = "tox"

  [[tool.poe.tasks.lint.args]]
  name = "envs"
  positional = true
  help = "List of tox envs to run."
  default = ""
