### tox

[tool.poe.tasks.tox]
help = "Run tox."
deps = ["_clone:ensure-repos:qpy"]
cmd = "tox"

  [[tool.poe.tasks.lint.args]]
  name = "envs"
  positional = true
  help = "List of tox envs to run."
  default = ""

### toxp

[tool.poe.tasks.toxp]
help = "Run tox (parallel)."
deps = ["_clone:ensure-repos:qpy"]
cmd = "tox -p"

  [[tool.poe.tasks.lint.args]]
  name = "envs"
  positional = true
  help = "List of tox envs to run."
  default = ""
