### typecheck

[tool.poe.tasks.typecheck]
help = "Run mypy type checker."
deps = ["_clone:ensure-repos:qpy"]
uses = { _repos = "_utils:parse-repos $repos" }
shell = """
  for repo in $_repos; do
    echo -e "${COLOR_TASK}[typecheck] ${COLOR_REPO}(${repo})${COLOR_OFF}"
    cd "${POE_ROOT}/questionpy/${repo}"
    mypy .
  done
"""

  [[tool.poe.tasks.typecheck.args]]
  name = "repos"
  positional = true
  multiple = true
  help = "List of repositories to type-check (sdk, server or all)."
  default = "all"
