[tool.poe.tasks."_utils:parse-repos"]
expr = """(
  "common sdk server"
  if repos == ["all"]
  else " ".join(sorted(set(repos)))
    if all(item in ["common", "sdk", "server"]
    for item in repos) else ""
)"""
args = [{ name = "repos", positional = true, multiple = true }]

[tool.poe.tasks."_utils:msg"]
shell = """
  echo -ne "${COLOR_TASK}[${task_name}]"
  [[ -n "${msg}" ]] && echo -ne " ${COLOR_MSG}${msg}"
  echo -e "${COLOR_OFF}"
"""
args = [
  { name = "task_name", positional = true, required = true },
  { name = "msg",       positional = true, default = "" },
]
