[tool.poe.tasks."_utils:ensure-docker"]
shell = """
  if ! $(docker info >/dev/null 2>&1); then
    echo 'Docker daemon is not running!'
    exit 1
  fi
"""

[tool.poe.tasks."_utils:git-clone"]
shell = """
  if [[ ! -d "$dir" ]]; then
    git clone --branch $branch $repo "$dir"
  else
    exit 0
  fi
"""
args = [
  { "name" = "repo",   positional = true, required = true },
  { "name" = "dir",    positional = true, required = true },
  { "name" = "branch", default = "dev" },
]

[tool.poe.tasks."_utils:hook"]
shell = """
  if [[ -n "${!name}" ]]; then
    echo "${msg}"
    eval "${!name}"
  fi
"""
args = [
  { "name" = "name", positional = true, required = true },
  { "name" = "msg",  positional = true, required = true },
]
